#!/usr/local/bin/bash

sxhkd &
"$HOME"/.config/polybar/launch.sh &

# -----------------------------------------
# bspwm config
# -----------------------------------------
#bspc config border_radius          5
bspc config top_padding            31
bspc config bottom_padding         -5
bspc config window_gap             4
bspc config border_width           3
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config honor_size_hints      true
#------------------------------------------------
# Border Colors
#------------------------------------------------
bspc config focused_border_color         "#FFFFFF"
bspc config active_border_color          "#5C5955"
bspc config normal_border_color          "#272822"
bspc config presel_border_color          "#F6F9FF"
bspc config focused_locked_border_color  "#CFB776"
bspc config active_locked_border_color   "#5C5955"
bspc config normal_locked_border_color   "#34322E"
bspc config focused_sticky_border_color  "#E3A5DA"
bspc config active_sticky_border_color   "#5C5955"
bspc config normal_sticky_border_color   "#34322E"
bspc config focused_private_border_color "#42CAD9"
bspc config active_private_border_color  "#5C5955"
bspc config normal_private_border_color  "#34322E"
bspc config urgent_border_color          "#F9A299"
# -----------------------------------------------
# Rules
# -----------------------------------------------
bspc rule -a "Firefox"  desktop=^3 follow=on
bspc rule -a TelegramDesktop=desktop ^1 follow=on
bspc rule -a Mpv follow=off state=floating
bspc rule -a Nitrogen center=on state=tiled
bspc rule -a GParted desktop='^5' follow=on focus=on
bspc rule -a urxvt  state=floating

bspc monitor -d CHAT TERM WEB CODE MEDIA
hsetroot -fill Walpapers/sundown.jpg &
#compton --config ~/.config/compton.conf -b &> /tmp/compton.log
